// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace SmartVectorDotNet;

// VectorMath.cs
partial class VectorMath
{
    public static partial Vector<T> Ceiling<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Ceiling(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Ceiling(d_));
        }
        throw new NotSupportedException();
    }

    public static partial Vector<T> Floor<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Floor(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Floor(d_));
        }
        throw new NotSupportedException();
    }

    public static partial Vector<T> Round<T>(in Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Round(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Round(x_));
        }
        throw new NotSupportedException();
    }

    public static partial Vector<T> Scale<T>(in Vector<T> n, in Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var n_ = ref Reinterpret<T, double>(n);
            ref readonly var x_ = ref Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Scale(n_, x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var n_ = ref Reinterpret<T, float>(n);
            ref readonly var x_ = ref Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Scale(n_, x_));
        }
        throw new NotSupportedException();
    }

    public static partial Vector<T> Truncate<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Truncate(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Truncate(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorMath._DivideLike.cs
partial class VectorMath
{
}

// VectorMath._ExponentialAndLogarithmic.cs
partial class VectorMath
{
    private static partial Vector<T> ExpCore<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(ExpCore(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(ExpCore(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorMath._Trigonometric.cs
partial class VectorMath
{
    public static partial Vector<T> Cos<T>(in Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Cos(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Cos(x_));
        }
        throw new NotSupportedException();
    }

    public static partial Vector<T> Sin<T>(in Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Sin(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Sin(x_));
        }
        throw new NotSupportedException();
    }

}

