// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>

using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
namespace SmartVectorDotNet;

partial class VectorMath
{

    public static partial Vector<T> Exp<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Exp(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Exp(d_));
        }
        throw new NotImplementedException();
    }


    public static partial Vector<T> Floor<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Floor(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Floor(d_));
        }
        throw new NotImplementedException();
    }


    public static partial Vector<T> Scale<T>(in Vector<T> n, in Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var n_ = ref Reinterpret<T, double>(n);
            ref readonly var x_ = ref Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Scale(n_, x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var n_ = ref Reinterpret<T, float>(n);
            ref readonly var x_ = ref Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Scale(n_, x_));
        }
        throw new NotImplementedException();
    }


    public static partial Vector<T> Truncate<T>(in Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Truncate(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Truncate(d_));
        }
        throw new NotImplementedException();
    }

}


