// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
namespace SmartVectorDotNet;

partial class ScalarOp
{
    #region Sqrt

    /// <summary> Operates sqrt. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Sqrt<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Sqrt(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Sqrt(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates sqrt. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Sqrt(double d) => Math.Sqrt(d);

    /// <summary> Operates sqrt. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Sqrt(float d_f) => MathF.Sqrt(d_f);


    #endregion Sqrt

    #region Cos

    /// <summary> Operates cos. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Cos<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Cos(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Cos(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates cos. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Cos(double d) => Math.Cos(d);

    /// <summary> Operates cos. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Cos(float d_f) => MathF.Cos(d_f);


    #endregion Cos

    #region Sin

    /// <summary> Operates sin. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Sin<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Sin(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Sin(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates sin. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Sin(double d) => Math.Sin(d);

    /// <summary> Operates sin. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Sin(float d_f) => MathF.Sin(d_f);


    #endregion Sin

    #region Tan

    /// <summary> Operates tan. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Tan<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Tan(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Tan(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates tan. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Tan(double d) => Math.Tan(d);

    /// <summary> Operates tan. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Tan(float d_f) => MathF.Tan(d_f);


    #endregion Tan

    #region Cosh

    /// <summary> Operates cosh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Cosh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Cosh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Cosh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates cosh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Cosh(double d) => Math.Cosh(d);

    /// <summary> Operates cosh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Cosh(float d_f) => MathF.Cosh(d_f);


    #endregion Cosh

    #region Sinh

    /// <summary> Operates sinh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Sinh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Sinh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Sinh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates sinh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Sinh(double d) => Math.Sinh(d);

    /// <summary> Operates sinh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Sinh(float d_f) => MathF.Sinh(d_f);


    #endregion Sinh

    #region Tanh

    /// <summary> Operates tanh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Tanh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Tanh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Tanh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates tanh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Tanh(double d) => Math.Tanh(d);

    /// <summary> Operates tanh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Tanh(float d_f) => MathF.Tanh(d_f);


    #endregion Tanh

    #region Acos

    /// <summary> Operates acos. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Acos<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Acos(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Acos(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates acos. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Acos(double d) => Math.Acos(d);

    /// <summary> Operates acos. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Acos(float d_f) => MathF.Acos(d_f);


    #endregion Acos

    #region Asin

    /// <summary> Operates asin. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Asin<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Asin(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Asin(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates asin. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Asin(double d) => Math.Asin(d);

    /// <summary> Operates asin. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Asin(float d_f) => MathF.Asin(d_f);


    #endregion Asin

    #region Atan

    /// <summary> Operates atan. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Atan<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Atan(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Atan(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates atan. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Atan(double d) => Math.Atan(d);

    /// <summary> Operates atan. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Atan(float d_f) => MathF.Atan(d_f);


    #endregion Atan

    #region Atan2

    /// <summary> Operates atan2. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="y"></param>
    /// <param name="x"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Atan2<T>(T y, T x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var y_ = Reinterpret<T, double>(y);
            var x_ = Reinterpret<T, double>(x);
            return Reinterpret<double, T>(Atan2(y_, x_));
        }
        if(typeof(T) == typeof(float))
        {
            var y_ = Reinterpret<T, float>(y);
            var x_ = Reinterpret<T, float>(x);
            return Reinterpret<float, T>(Atan2(y_, x_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates atan2. </summary>
    /// <param name="y"></param>
    /// <param name="x"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Atan2(double y, double x) => Math.Atan2(y, x);

    /// <summary> Operates atan2. </summary>
    /// <param name="y_f"></param>
    /// <param name="x_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Atan2(float y_f, float x_f) => MathF.Atan2(y_f, x_f);


    #endregion Atan2

    #region Ceiling

    /// <summary> Operates ceiling. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Ceiling<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Ceiling(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Ceiling(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates ceiling. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Ceiling(double d) => Math.Ceiling(d);

    /// <summary> Operates ceiling. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Ceiling(float d_f) => MathF.Ceiling(d_f);


    #endregion Ceiling

    #region Floor

    /// <summary> Operates floor. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Floor<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Floor(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Floor(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates floor. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Floor(double d) => Math.Floor(d);

    /// <summary> Operates floor. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Floor(float d_f) => MathF.Floor(d_f);


    #endregion Floor

    #region Exp

    /// <summary> Operates exp. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Exp<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Exp(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Exp(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates exp. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Exp(double d) => Math.Exp(d);

    /// <summary> Operates exp. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Exp(float d_f) => MathF.Exp(d_f);


    #endregion Exp

    #region Pow

    /// <summary> Operates pow. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="x"></param>
    /// <param name="y"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Pow<T>(T x, T y)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var x_ = Reinterpret<T, double>(x);
            var y_ = Reinterpret<T, double>(y);
            return Reinterpret<double, T>(Pow(x_, y_));
        }
        if(typeof(T) == typeof(float))
        {
            var x_ = Reinterpret<T, float>(x);
            var y_ = Reinterpret<T, float>(y);
            return Reinterpret<float, T>(Pow(x_, y_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates pow. </summary>
    /// <param name="x"></param>
    /// <param name="y"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Pow(double x, double y) => Math.Pow(x, y);

    /// <summary> Operates pow. </summary>
    /// <param name="x_f"></param>
    /// <param name="y_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Pow(float x_f, float y_f) => MathF.Pow(x_f, y_f);


    #endregion Pow

    #region Log

    /// <summary> Operates log. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Log<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Log(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Log(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates log. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Log(double d) => Math.Log(d);

    /// <summary> Operates log. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Log(float d_f) => MathF.Log(d_f);


    #endregion Log

    #region Log

    /// <summary> Operates log. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <param name="newBase"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Log<T>(T d, T newBase)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            var newBase_ = Reinterpret<T, double>(newBase);
            return Reinterpret<double, T>(Log(d_, newBase_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            var newBase_ = Reinterpret<T, float>(newBase);
            return Reinterpret<float, T>(Log(d_, newBase_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates log. </summary>
    /// <param name="d"></param>
    /// <param name="newBase"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Log(double d, double newBase) => Math.Log(d, newBase);

    /// <summary> Operates log. </summary>
    /// <param name="d_f"></param>
    /// <param name="newBase_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Log(float d_f, float newBase_f) => MathF.Log(d_f, newBase_f);


    #endregion Log

    #region Log10

    /// <summary> Operates log10. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Log10<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Log10(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Log10(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates log10. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Log10(double d) => Math.Log10(d);

    /// <summary> Operates log10. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Log10(float d_f) => MathF.Log10(d_f);


    #endregion Log10

    #region Round

    /// <summary> Operates round. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Round<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Round(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Round(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates round. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Round(double d) => Math.Round(d);

    /// <summary> Operates round. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Round(float d_f) => MathF.Round(d_f);


    #endregion Round

    #region Truncate

    /// <summary> Operates truncate. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Truncate<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Truncate(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Truncate(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates truncate. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static double Truncate(double d) => Math.Truncate(d);

    /// <summary> Operates truncate. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static float Truncate(float d_f) => MathF.Truncate(d_f);


    #endregion Truncate

    #region Acosh

    /// <summary> Operates acosh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Acosh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Acosh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Acosh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates acosh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial double Acosh(double d);

    /// <summary> Operates acosh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial float Acosh(float d_f);

    #if NETSTANDARD2_1_OR_GREATER || NET6_0_OR_GREATER
    public static partial double Acosh(double d) => Math.Acosh(d);
    public static partial float  Acosh(float d_f) => MathF.Acosh(d_f);
    #else
    public static partial double Acosh(double d) => MathEx.Acosh(d);
    public static partial float  Acosh(float d_f) => MathEx.Acosh(d_f);
    #endif

    #endregion Acosh

    #region Asinh

    /// <summary> Operates asinh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Asinh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Asinh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Asinh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates asinh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial double Asinh(double d);

    /// <summary> Operates asinh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial float Asinh(float d_f);

    #if NETSTANDARD2_1_OR_GREATER || NET6_0_OR_GREATER
    public static partial double Asinh(double d) => Math.Asinh(d);
    public static partial float  Asinh(float d_f) => MathF.Asinh(d_f);
    #else
    public static partial double Asinh(double d) => MathEx.Asinh(d);
    public static partial float  Asinh(float d_f) => MathEx.Asinh(d_f);
    #endif

    #endregion Asinh

    #region Atanh

    /// <summary> Operates atanh. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Atanh<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Atanh(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Atanh(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates atanh. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial double Atanh(double d);

    /// <summary> Operates atanh. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial float Atanh(float d_f);

    #if NETSTANDARD2_1_OR_GREATER || NET6_0_OR_GREATER
    public static partial double Atanh(double d) => Math.Atanh(d);
    public static partial float  Atanh(float d_f) => MathF.Atanh(d_f);
    #else
    public static partial double Atanh(double d) => MathEx.Atanh(d);
    public static partial float  Atanh(float d_f) => MathEx.Atanh(d_f);
    #endif

    #endregion Atanh

    #region Cbrt

    /// <summary> Operates cbrt. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Cbrt<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Cbrt(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Cbrt(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates cbrt. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial double Cbrt(double d);

    /// <summary> Operates cbrt. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial float Cbrt(float d_f);

    #if NETSTANDARD2_1_OR_GREATER || NET6_0_OR_GREATER
    public static partial double Cbrt(double d) => Math.Cbrt(d);
    public static partial float  Cbrt(float d_f) => MathF.Cbrt(d_f);
    #else
    public static partial double Cbrt(double d) => MathEx.Cbrt(d);
    public static partial float  Cbrt(float d_f) => MathEx.Cbrt(d_f);
    #endif

    #endregion Cbrt

    #region Log2

    /// <summary> Operates log2. </summary>
    /// <typeparam name="T"></typeparam>
    /// <param name="d"></param>
    /// <returns></returns>
    /// <exception cref="NotSupportedException" />
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static T Log2<T>(T d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            var d_ = Reinterpret<T, double>(d);
            return Reinterpret<double, T>(Log2(d_));
        }
        if(typeof(T) == typeof(float))
        {
            var d_ = Reinterpret<T, float>(d);
            return Reinterpret<float, T>(Log2(d_));
        }
        throw new NotSupportedException();
    }

    /// <summary> Operates log2. </summary>
    /// <param name="d"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial double Log2(double d);

    /// <summary> Operates log2. </summary>
    /// <param name="d_f"></param>
    /// <returns></returns>
    [GeneratedCode("T4", null), MethodImpl(_inlining)]
    public static partial float Log2(float d_f);

    #if NET6_0_OR_GREATER
    public static partial double Log2(double d) => Math.Log2(d);
    public static partial float  Log2(float d_f) => MathF.Log2(d_f);
    #else
    public static partial double Log2(double d) => Log(d, 2);
    public static partial float  Log2(float d_f) => Log(d_f, 2);
    #endif

    #endregion Log2

}

