using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace SmartVectorDotNet;


public partial class VectorizationTest
{
    // Void UnaryMinus[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Complement[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void GreaterThan[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void GreaterThanOrEquals[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void GreaterThanOrEquals[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void GreaterThanOrEquals[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Sqrt[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Cos[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Sin[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Tan[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Cosh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Sinh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Tanh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Acos[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Asin[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Atan[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Atan2[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Acosh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Asinh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Atanh[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Cbrt[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Log2[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Ceiling[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Floor[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Exp[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Pow[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Log[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Log[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Log10[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Round[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Truncate[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Scale[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void UnaryPlus[T](System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Add[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Add[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void Add[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Subtract[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Subtract[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void Subtract[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Multiply[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Multiply[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void Multiply[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Divide[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Divide[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void Divide[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseAnd[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseAnd[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void BitwiseAnd[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseOr[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseOr[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void BitwiseOr[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseXor[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void BitwiseXor[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void BitwiseXor[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Equals[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void Equals[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void Equals[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void LessThan[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void LessThan[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void LessThan[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void LessThanOrEquals[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void LessThanOrEquals[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
    // Void LessThanOrEquals[T](System.ReadOnlySpan`1[T], System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void GreaterThan[T](T, System.ReadOnlySpan`1[T], System.Span`1[T])
    // Void GreaterThan[T](System.ReadOnlySpan`1[T], T, System.Span`1[T])
}