using System;
using System.Collections.Immutable;
using System.Linq;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGeneratorToolkit;

namespace SmartVectorDotNet.Generators;

/// <summary>
/// Provides an interceptor that replaces the Calculate method with an optimized version
/// by automatically generating a strategy type based on the lambda expression.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed partial class VectorizationCalculatorGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitConstants);

        var source = context.SyntaxProvider.CreateSyntaxProvider(
            InterceptorPredicate,
            InterceptorTransform)
            .Where(static x => x is not null);

        context.RegisterSourceOutput(
            source,
            EmitSource!);
    }


    private static bool InterceptorPredicate(SyntaxNode node, CancellationToken token) =>
        node is InvocationExpressionSyntax {
            Expression: MemberAccessExpressionSyntax {
                Name.Identifier.Text: "Calculate"
            }
        };


    private static InterceptorInfo? InterceptorTransform(GeneratorSyntaxContext context, CancellationToken token)
    {
        if (context.Node is not InvocationExpressionSyntax invocation)
        {
            return null;
        }
        if (context.SemanticModel.GetSymbolInfo(invocation).Symbol is not IMethodSymbol methodSymbol)
        {
            return null;
        }
        if (!methodSymbol.IsGenericMethod)
        {
            return null;
        }
        var methodIdentifier = methodSymbol.OriginalDefinition.ToDisplayString();
        if (!methodIdentifier.StartsWith("SmartVectorDotNet.Vectorization.Calculate<T>"))
        {
            return null;
        }
        var targetType = methodSymbol.TypeArguments[0].ToDisplayString();
        if (context.SemanticModel.GetInterceptableLocation(invocation) is not { } location)
        {
            return null;
        }
        if (invocation.ArgumentList.Arguments[0].Expression is not LambdaExpressionSyntax lambda)
        {
            return null;
        }
        var parameters = invocation.ArgumentList.Arguments[0].Expression switch
        {
            SimpleLambdaExpressionSyntax x => [x.Parameter.Identifier.Text],
            ParenthesizedLambdaExpressionSyntax x => x.ParameterList.Parameters.Select(static x => x.Identifier.Text).ToImmutableArray(),
            _ => [],
        };
        if(parameters.Length == 0)
        {
            return null;
        }
        if(lambda.ExpressionBody is not { } expr)
        {
            return null;
        }
        var sclexpr = $"{expr}";
        var vctexpr = $"{new ScalarOpToVectorOpVisitor(context.SemanticModel).Visit(lambda.ExpressionBody)}";
        return new(location, targetType, sclexpr, $"{vctexpr}", parameters);
    }


    private static void EmitConstants(IncrementalGeneratorPostInitializationContext context)
    {
        var sb = new SourceBuilderSlim();
        sb.AppendLine($$"""
                // <auto-generated>
                // This file is auto-generated by SmartVectorDotNet.Generators.VectorizationCalculatorGenerator
                // Do not edit this file manually.
                // </auto-generated>
                
                using System;
                using System.Collections.Generic;
                using System.Linq;
                namespace SmartVectorDotNet;
            
                internal static class VectorizationExtensions
                {
                """);
        for(var i = 1; i <= 10; ++i)
        {
            sb.AppendLine($$"""
                    /// <summary>
                    /// Calculates vectorized operation on the input spans and writes the result to the answer span.
                    /// </summary>
                    /// <typeparam name="T"></typeparam>
                    /// <param name="strategy"></param>
                    /// <param name="operation"></param>
                    {{ Enumerable.Range(1, i).Select(static x => $"/// <param name=\"x{x}\"></param>").PreserveIndent() }}
                    /// <param name="ans"></param>
                    /// <remarks>
                    /// This method is intended to be intercepted by source generator.
                    /// </remarks>
                    public static void Calculate<T>(
                        this Vectorization strategy,
                        Func<{{string.Join(", ", Enumerable.Repeat("T", i))}}, T> operation,
                        {{Enumerable.Range(1, i).Select(static x => $"ReadOnlySpan<T> x{x},").PreserveIndent()}}
                        Span<T> ans)
                        where T : unmanaged
                    {
                        {{Enumerable.Range(1, i).Select(static x => $"Guard.ValidArgument(x{x}.Length == ans.Length, \"`x{x}` and `ans` must have same length.\");").PreserveIndent()}}
                        {{Enumerable.Range(1, i).Select(static x => $"using var safeX{x}Buffer = Vectorization.EnsureSourceSafe(ref x{x}, ans);").PreserveIndent()}}
                        throw new NotImplementedException();
                    }

                """);
        }
        sb.AppendLine($$"""
                }
                """);

        context.AddSource(
            "SmartVectorDotNet.VectorizationExtensions.Calculate.g.cs",
            sb.Build());
    }


    private static void EmitSource(SourceProductionContext context, InterceptorInfo source)
    {
        var sb = new SourceBuilderSlim();
        var elementType = source.TargetType;
        sb.AppendLine($$"""
            // <auto-generated>
            // This (.cs) file is generated by source generator.
            // Do not change it. change the SmartVectorDotNet.Generators.VectorizationCalculatorGenerator instead.
            // </auto-generated>
            #nullable enable
            namespace System.Runtime.CompilerServices
            {
                // this type is needed by the compiler to implement interceptors,
                // it doesn't need to come from the runtime itself

                [System.AttributeUsage(AttributeTargets.Method, AllowMultiple = true)]
                sealed file class InterceptsLocationAttribute : Attribute
                {
                    public InterceptsLocationAttribute(int version, string data)
                    {
                        _ = version;
                        _ = data;
                    }
                }
            }

            namespace SmartVectorDotNet.Generated
            {
                static file class VectorizationCalculatorInterceptors
                {
                    [System.Runtime.CompilerServices.InterceptsLocation(version: {{source.Location.Version}}, data: "{{source.Location.Data}}")]
                    public static void Calculate(
                        this Vectorization strategy,
                        System.Func<{{string.Join(", ", source.Arguments.Select(x => elementType))}}, {{elementType}}> operation,
                        {{source.Arguments.Select(x => $"System.ReadOnlySpan<{elementType}> {x},").PreserveIndent()}}
                        System.Span<{{elementType}}> ans)
                    {
                        strategy.Calculate<{{elementType}}, Operation>({{string.Join(", ", source.Arguments)}}, ans);
                    }
                }

                file readonly struct Operation : IVectorFormula{{source.Arguments.Length}}<{{elementType}}>
                {
                    public {{elementType}} Calculate({{string.Join(", ", source.Arguments.Select(x => $"{elementType} {x}"))}})
                    {
                        return {{source.ScalarOpExpression}};
                    }

                    public System.Numerics.Vector<{{elementType}}> Calculate({{string.Join(", ", source.Arguments.Select(x => $"System.Numerics.Vector<{elementType}> {x}"))}})
                    {
                        return {{source.VectorOpExpression}};
                    }
                }
            }
            """);
        context.AddSource(source.Location.Data.Replace('/', '-').Replace('=', '.') + ".g.cs", sb.Build());
    }
}


internal sealed record class InterceptorInfo(
    InterceptableLocation Location,
    string TargetType,
    string ScalarOpExpression,
    string VectorOpExpression,
    ImmutableArray<string> Arguments
    ) : IEquatable<InterceptorInfo>
{
    public override int GetHashCode() =>
        Location.GetHashCode() ^ TargetType.GetHashCode() ^ Arguments.Length;

    public bool Equals(InterceptorInfo? other) =>
        other is not null &&
        Location.Equals(other.Location) &&
        TargetType == other.TargetType &&
        ScalarOpExpression == other.ScalarOpExpression &&
        VectorOpExpression == other.VectorOpExpression &&
        Arguments.SequenceEqual(other.Arguments);
}


file sealed class ScalarOpToVectorOpVisitor(SemanticModel semanticModel) : CSharpSyntaxVisitor<SyntaxNode>
{

    public override SyntaxNode DefaultVisit(SyntaxNode node) =>
        node.ReplaceNodes(node.ChildNodes(), (original, _) => Visit(original)!);

    public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
    {
        var x = semanticModel.GetSymbolInfo(node).Symbol;
        if (x is INamedTypeSymbol typeSymbol && typeSymbol.ToDisplayString() == "SmartVectorDotNet.ScalarOp")
        {
            return SyntaxFactory.IdentifierName("SmartVectorDotNet.VectorOp");
        }
        return base.VisitIdentifierName(node);
    }
}