using Microsoft.CodeAnalysis;
using SourceGeneratorToolkit;

namespace SmartVectorDotNet.Generators.Internal;

/// <summary>
/// Provides a generator for <see cref="SmartVectorDotNet.ParallelVectorization"/>.
/// </summary>
[Generator(LanguageNames.CSharp)]
internal class ParallelVectorizationGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(EmitAttribute);
        var source = context.SyntaxProvider.ForAttributeWithMetadataName(
            "SmartVectorDotNet.Internal.ParallelVectorizationAttribute",
            static (node, token) => true,
            static (context, token) => (INamedTypeSymbol)context.TargetSymbol);
        context.RegisterSourceOutput(source, EmitImplementation);
     }

    private static void EmitAttribute(IncrementalGeneratorPostInitializationContext context)
        => context.AddSource(
            "ParallelVectorization.Attribute.g.cs",
            """
            // <auto-generated>
            // This (.cs) file is generated by source generator.
            // Do not change it. change the SmartVectorDotNet.Generators.Internal.ParallelVectorizationGenerator instead.
            // </auto-generated>
            namespace SmartVectorDotNet.Internal;

            [AttributeUsage(AttributeTargets.Class)]
            internal sealed class ParallelVectorizationAttribute : Attribute;

            """);

    private static void EmitImplementation(SourceProductionContext context, INamedTypeSymbol parallelVectorizationTypeSymbol)
    {
        var vectorizationTypeSymbol = parallelVectorizationTypeSymbol.BaseType!;
        var methods = vectorizationTypeSymbol
            .GetMembers()
            .OfType<IMethodSymbol>()
            .Where(static m
                => m.DeclaredAccessibility == Accessibility.ProtectedOrInternal
                && m.IsVirtual
                && m.ReturnsVoid
                && m.Name.EndsWith("Core"));
        var sb = new SourceBuilderSlim();
        sb.AppendLine($$"""
            // <auto-generated>
            // This (.cs) file is generated by source generator.
            // Do not change it. change the SmartVectorDotNet.Generators.Internal.ParallelVectorizationGenerator instead.
            // </auto-generated>
            using System;
            using System.Threading.Tasks;
            using SmartVectorDotNet.Internal;
            namespace SmartVectorDotNet;

            unsafe partial class ParallelVectorization
            {
            """);
        foreach (var method in methods)
        {
            string typeParamsDecl;
            string paramsDecl = string.Join(", ", method.Parameters.Select(static p => $"{p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)} {p.Name}"));
            if (method.IsGenericMethod)
            {
                typeParamsDecl = "<" + string.Join(", ", method.TypeParameters.Select(static t => t.Name)) + ">";
            }
            else
            {
                typeParamsDecl = "";
            }
            var spanParams = method.Parameters
                .Where(static p => IsSpanType(p.Type))
                .ToArray();
            var nonSpanParams = method.Parameters
                .Where(static p => !IsSpanType(p.Type))
                .ToArray();
            var stateDeconstruct = string.Join(
                ", ",
                [
                    "@this", "i",
                    ..nonSpanParams.Select(static p => p.Name),
                    ..spanParams.Select(static p => $"{p.Name}Pinned"),
                ]);
            var stateConstruct = string.Join(
                ", ",
                [
                    "this", "i",
                    ..nonSpanParams.Select(static p => p.Name),
                    ..spanParams.Select(static p => $"{p.Name}Pinned"),
                ]);
            var stateType = string.Join(
                ", ",
                [
                    "ParallelVectorization", "int",
                    ..nonSpanParams.Select(static p => p.Type.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat)),
                    ..spanParams.Select(static p => $"PinnedBuffer<{getSpanElementName(p)}>"),
                ]
                );
            var args = string.Join(
                ", ",
                [
                    ..nonSpanParams.Select(static p => p.Name),
                    ..spanParams.Select(static p => $"{p.Name}Span"),
                ]);
            sb.AppendLine($$"""
                /// <inheritdoc />
                protected internal override void {{method.Name}}{{typeParamsDecl}}({{paramsDecl}})
                {
                    var parallelCount = Math.Min(ParallelCount, ans.Length);
                    var tasks = new Task[ParallelCount];
                    {{
                        spanParams
                            .Select(static p => $"fixed({getSpanElementName(p)}* {p.Name}Ptr = {p.Name})")
                            .PreserveIndent()
                    }}
                    {
                        {{
                            spanParams
                                .Select(static p => $"var {p.Name}Pinned = new PinnedBuffer<{getSpanElementName(p)}>({p.Name}Ptr, {p.Name}.Length);")
                                .PreserveIndent()
                        }}
                        for (var i = 0; i < ParallelCount; ++i)
                        {
                            tasks[i] = Task.Factory.StartNew(static state =>
                            {
                                var ({{stateDeconstruct}}) = (({{stateType}}))state!;
                                var start = i * {{spanParams[spanParams.Length - 1].Name}}Pinned.Length / @this.ParallelCount;
                                var end = (i + 1) * {{spanParams[spanParams.Length - 1].Name}}Pinned.Length / @this.ParallelCount;
                                {{
                                    spanParams
                                        .Select(static p => $"var {p.Name}Span = {p.Name}Pinned.AsSpan()[start..end];")
                                        .PreserveIndent()
                                }}
                                @this.Entity.{{method.Name}}{{typeParamsDecl}}({{args}});
                            }, ({{stateConstruct}}));
                        }
                        Task.WaitAll(tasks);
                    }
                }

            """);
        }
        sb.AppendLine("""
            }

            """);
        context.AddSource("ParallelVectorization.g.cs", sb.Build());

        static string getSpanElementName(IParameterSymbol p)
            => ((INamedTypeSymbol)p.Type).TypeArguments[0].ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
    }

    private static bool IsSpanType(ITypeSymbol typeSymbol)
    {
        if (typeSymbol is not INamedTypeSymbol namedTypeSymbol)
        {
            return false;
        }
        var fullName = namedTypeSymbol.ToDisplayString();
        return fullName.StartsWith("System.Span<") || fullName.StartsWith("System.ReadOnlySpan<");
    }
}
