// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
#nullable enable
using System.CodeDom.Compiler;

namespace SmartVectorDotNet;


/// <summary>
/// Vectorized function with 1 input.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc1<T>(
    ReadOnlySpan<T> x1,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 2 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc2<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 3 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc3<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 4 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc4<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 5 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc5<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 6 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="x6"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc6<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    ReadOnlySpan<T> x6,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 7 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="x6"></param>
/// <param name="x7"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc7<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    ReadOnlySpan<T> x6,
    ReadOnlySpan<T> x7,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 8 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="x6"></param>
/// <param name="x7"></param>
/// <param name="x8"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc8<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    ReadOnlySpan<T> x6,
    ReadOnlySpan<T> x7,
    ReadOnlySpan<T> x8,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 9 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="x6"></param>
/// <param name="x7"></param>
/// <param name="x8"></param>
/// <param name="x9"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc9<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    ReadOnlySpan<T> x6,
    ReadOnlySpan<T> x7,
    ReadOnlySpan<T> x8,
    ReadOnlySpan<T> x9,
    Span<T> ans)
    where T : unmanaged;


/// <summary>
/// Vectorized function with 10 inputs.
/// </summary>
/// <typeparam name="T"></typeparam>
/// <param name="x1"></param>
/// <param name="x2"></param>
/// <param name="x3"></param>
/// <param name="x4"></param>
/// <param name="x5"></param>
/// <param name="x6"></param>
/// <param name="x7"></param>
/// <param name="x8"></param>
/// <param name="x9"></param>
/// <param name="x10"></param>
/// <param name="ans"></param>
[GeneratedCode("T4", null)]
public delegate void VectorizedFunc10<T>(
    ReadOnlySpan<T> x1,
    ReadOnlySpan<T> x2,
    ReadOnlySpan<T> x3,
    ReadOnlySpan<T> x4,
    ReadOnlySpan<T> x5,
    ReadOnlySpan<T> x6,
    ReadOnlySpan<T> x7,
    ReadOnlySpan<T> x8,
    ReadOnlySpan<T> x9,
    ReadOnlySpan<T> x10,
    Span<T> ans)
    where T : unmanaged;

