// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
#nullable enable
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Numerics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

namespace SmartVectorDotNet;

#region unaryplus

partial class Vectorization
{
    /// <summary>
    /// Operates unaryplus for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void UnaryPlus<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(x.Length == ans.Length, "`x` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref x, ans);
        unsafe
        {
            UnaryPlusCore(x, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="UnaryPlus{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void UnaryPlusCore<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.UnaryPlus(x[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void UnaryPlusCore<T>(ReadOnlySpan<T> x, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(x);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] =  vectorX[i];
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            x.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) =  Unsafe.As<T, Vector<T>>(ref vx[0]); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region unaryminus

partial class Vectorization
{
    /// <summary>
    /// Operates unaryminus for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void UnaryMinus<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(x.Length == ans.Length, "`x` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref x, ans);
        unsafe
        {
            UnaryMinusCore(x, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="UnaryMinus{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void UnaryMinusCore<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.UnaryMinus(x[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void UnaryMinusCore<T>(ReadOnlySpan<T> x, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(x);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = -vectorX[i];
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            x.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = -Unsafe.As<T, Vector<T>>(ref vx[0]); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region complement

partial class Vectorization
{
    /// <summary>
    /// Operates complement for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Complement<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(x.Length == ans.Length, "`x` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref x, ans);
        unsafe
        {
            ComplementCore(x, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Complement{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="x"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void ComplementCore<T>(ReadOnlySpan<T> x, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Complement(x[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void ComplementCore<T>(ReadOnlySpan<T> x, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(x);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = ~vectorX[i];
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            x.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = ~Unsafe.As<T, Vector<T>>(ref vx[0]); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region abs

partial class Vectorization
{
    /// <summary>
    /// Operates abs for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Abs<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AbsCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Abs{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AbsCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Abs(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AbsCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Abs(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Abs(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region acos

partial class Vectorization
{
    /// <summary>
    /// Operates acos for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Acos<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AcosCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Acos{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AcosCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Acos(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AcosCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Acos(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Acos(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region acosh

partial class Vectorization
{
    /// <summary>
    /// Operates acosh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Acosh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AcoshCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Acosh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AcoshCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Acosh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AcoshCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Acosh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Acosh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region asin

partial class Vectorization
{
    /// <summary>
    /// Operates asin for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Asin<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AsinCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Asin{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AsinCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Asin(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AsinCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Asin(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Asin(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region asinh

partial class Vectorization
{
    /// <summary>
    /// Operates asinh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Asinh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AsinhCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Asinh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AsinhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Asinh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AsinhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Asinh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Asinh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region atan

partial class Vectorization
{
    /// <summary>
    /// Operates atan for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Atan<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AtanCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Atan{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AtanCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Atan(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AtanCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Atan(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Atan(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region atanh

partial class Vectorization
{
    /// <summary>
    /// Operates atanh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Atanh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            AtanhCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Atanh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void AtanhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Atanh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void AtanhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Atanh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Atanh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region cbrt

partial class Vectorization
{
    /// <summary>
    /// Operates cbrt for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Cbrt<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            CbrtCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Cbrt{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void CbrtCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Cbrt(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void CbrtCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Cbrt(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Cbrt(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region ceiling

partial class Vectorization
{
    /// <summary>
    /// Operates ceiling for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Ceiling<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            CeilingCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Ceiling{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void CeilingCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Ceiling(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void CeilingCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Ceiling(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Ceiling(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region cos

partial class Vectorization
{
    /// <summary>
    /// Operates cos for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Cos<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            CosCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Cos{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void CosCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Cos(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void CosCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Cos(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Cos(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region cosh

partial class Vectorization
{
    /// <summary>
    /// Operates cosh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Cosh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            CoshCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Cosh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void CoshCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Cosh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void CoshCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Cosh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Cosh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region exp

partial class Vectorization
{
    /// <summary>
    /// Operates exp for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Exp<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            ExpCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Exp{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void ExpCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Exp(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void ExpCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Exp(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Exp(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region floor

partial class Vectorization
{
    /// <summary>
    /// Operates floor for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Floor<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            FloorCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Floor{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void FloorCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Floor(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void FloorCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Floor(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Floor(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region log

partial class Vectorization
{
    /// <summary>
    /// Operates log for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Log<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            LogCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Log{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void LogCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Log(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void LogCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Log(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Log(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region log10

partial class Vectorization
{
    /// <summary>
    /// Operates log10 for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Log10<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            Log10Core(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Log10{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void Log10Core<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Log10(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void Log10Core<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Log10(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Log10(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region log2

partial class Vectorization
{
    /// <summary>
    /// Operates log2 for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Log2<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            Log2Core(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Log2{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void Log2Core<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Log2(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void Log2Core<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Log2(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Log2(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region round

partial class Vectorization
{
    /// <summary>
    /// Operates round for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Round<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            RoundCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Round{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void RoundCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Round(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void RoundCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Round(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Round(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region sign

partial class Vectorization
{
    /// <summary>
    /// Operates sign for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Sign<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            SignCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Sign{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void SignCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Sign(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void SignCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Sign(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Sign(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region sin

partial class Vectorization
{
    /// <summary>
    /// Operates sin for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Sin<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            SinCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Sin{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void SinCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Sin(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void SinCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Sin(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Sin(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region sinh

partial class Vectorization
{
    /// <summary>
    /// Operates sinh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Sinh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            SinhCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Sinh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void SinhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Sinh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void SinhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Sinh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Sinh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region sqrt

partial class Vectorization
{
    /// <summary>
    /// Operates sqrt for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Sqrt<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            SqrtCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Sqrt{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void SqrtCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Sqrt(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void SqrtCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Sqrt(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Sqrt(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region tan

partial class Vectorization
{
    /// <summary>
    /// Operates tan for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Tan<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            TanCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Tan{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void TanCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Tan(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void TanCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Tan(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Tan(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region tanh

partial class Vectorization
{
    /// <summary>
    /// Operates tanh for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Tanh<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            TanhCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Tanh{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void TanhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Tanh(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void TanhCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Tanh(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Tanh(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

#region truncate

partial class Vectorization
{
    /// <summary>
    /// Operates truncate for each corresponding elements of operands.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="ArgumentException"> <paramref name="ans" /> and all span operands must have same length. </exception>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    [GeneratedCode("T4", null)]
    public void Truncate<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        Guard.ValidArgument(d.Length == ans.Length, "`d` and `ans` must have same length.");
        using var safeXBuffer = EnsureSourceSafe(ref d, ans);
        unsafe
        {
            TruncateCore(d, ans);
        }
    }

    /// <summary>
    /// Core implementation for <see cref="Truncate{T}(ReadOnlySpan{T}, Span{T})" />.
    /// For this method it is ensured that all parameters have same length.
    /// </summary>
    /// <typeparam name="T"> The type of elements. </typeparam>
    /// <param name="d"> The 1st operand elements. </param>
    /// <param name="ans"> The destination of answer. </param>
    /// <exception cref="NotSupportedException"> The operation for <typeparamref name="T"/> is not supported. </exception>
    /// <remarks>
    /// For this method it is ensured followings:
    /// <list type="bullet">
    /// <item> all parameters have same length </item>
    /// <item> there are no offseted overlap between input and output (it means writing to the same index is safe) </item>
    /// </list>
    /// </remarks>
    [GeneratedCode("T4", null), UnsafeApi]
    protected internal virtual void TruncateCore<T>(ReadOnlySpan<T> d, Span<T> ans)
        where T : unmanaged
    {
        for (var i = 0; i < ans.Length; ++i)
            ans[i] = ScalarOp.Truncate(d[i]);
    }
}

partial class SimdVectorization
{
    /// <inheritdoc />
    [GeneratedCode("T4", null)]
    protected internal override sealed void TruncateCore<T>(ReadOnlySpan<T> d, Span<T> ans)
    {
        var vectorX = MemoryMarshal.Cast<T, Vector<T>>(d);
        var vectorAns = MemoryMarshal.Cast<T, Vector<T>>(ans);
        var vectorLength = vectorAns.Length * Vector<T>.Count;
        for(var i = 0; i < vectorAns.Length; ++i)
        {
            vectorAns[i] = VectorOp.Truncate(vectorX[i]);
        }
        if(vectorLength < ans.Length)
        {
            var vx = (stackalloc T[Vector<T>.Count]);
            var vans = (stackalloc T[Vector<T>.Count]);
            d.Slice(vectorLength).CopyTo(vx);
            Unsafe.As<T, Vector<T>>(ref vans[0]) = VectorOp.Truncate(Unsafe.As<T, Vector<T>>(ref vx[0])); 
            vans.Slice(0, ans.Length - vectorLength).CopyTo(ans.Slice(vectorLength));
        }
    }
}

#endregion

