// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Text;

namespace SmartVectorDotNet;

partial class VectorOp
{
    /// <summary>
    /// Provides constant definitions.
    /// </summary>
    /// <typeparam name="T"></typeparam>
    public partial class Const<T>
        where T : unmanaged
    {
        /// <summary> Gets the vector which has <c>0</c> values. </summary>
        public static readonly Vector<T> Zero;
        
        /// <summary> Gets the vector which has <c>1</c> values. </summary>
        public static readonly Vector<T> One;
        
        /// <summary> Gets the vector which has <c>T.MinValue</c> values. </summary>
        public static readonly Vector<T> MinValue;
        
        /// <summary> Gets the vector which has <c>T.MaxValue</c> values. </summary>
        public static readonly Vector<T> MaxValue;

        /// <summary> Gets the vector which has values whose MSB is 1. </summary>
        public static readonly Vector<T> Msb;
        
        /// <summary> Gets the vector which has values whose MSB is 1. </summary>
        public static readonly Vector<T> Lsb;

        static Const()
        {
            if(typeof(T) == typeof(nuint))
            {
                Unsafe.As<Vector<T>, Vector<nuint>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<nuint>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<nuint>>(ref Lsb) = new(1);
                Unsafe.As<Vector<T>, Vector<nuint>>(ref Msb) = new((nuint)(1uL << (Unsafe.SizeOf<nuint>() * 8 - 1)));
                if(IntPtr.Size == 8)
                {
                    Unsafe.As<Vector<T>, Vector<nuint>>(ref MinValue) = new(unchecked((nuint)ulong.MinValue));
                    Unsafe.As<Vector<T>, Vector<nuint>>(ref MaxValue) = new(unchecked((nuint)ulong.MaxValue));
                }
                else
                {
                    Unsafe.As<Vector<T>, Vector<nuint>>(ref MinValue) = new((nuint)uint.MinValue);
                    Unsafe.As<Vector<T>, Vector<nuint>>(ref MaxValue) = new((nuint)uint.MaxValue);
                }
            }
            else if(typeof(T) == typeof(nint))
            {
                Unsafe.As<Vector<T>, Vector<nint>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<nint>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<nint>>(ref Lsb) = new(1);
                Unsafe.As<Vector<T>, Vector<nint>>(ref Msb) = new((nint)(1uL << (Unsafe.SizeOf<nint>() * 8 - 1)));
                if(IntPtr.Size == 8)
                {
                    Unsafe.As<Vector<T>, Vector<nint>>(ref MinValue) = new(unchecked((nint)long.MinValue));
                    Unsafe.As<Vector<T>, Vector<nint>>(ref MaxValue) = new(unchecked((nint)long.MaxValue));
                }
                else
                {
                    Unsafe.As<Vector<T>, Vector<nint>>(ref MinValue) = new((nint)int.MinValue);
                    Unsafe.As<Vector<T>, Vector<nint>>(ref MaxValue) = new((nint)int.MaxValue);
                }
            }
            else if(typeof(T) == typeof(byte))
            {
                Unsafe.As<Vector<T>, Vector<byte>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<byte>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<byte>>(ref MinValue) = new(byte.MinValue);
                Unsafe.As<Vector<T>, Vector<byte>>(ref MaxValue) = new(byte.MaxValue);
                Unsafe.As<Vector<T>, Vector<byte>>(ref Msb) = new((byte)(1uL << (sizeof(byte) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<byte>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(ushort))
            {
                Unsafe.As<Vector<T>, Vector<ushort>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<ushort>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<ushort>>(ref MinValue) = new(ushort.MinValue);
                Unsafe.As<Vector<T>, Vector<ushort>>(ref MaxValue) = new(ushort.MaxValue);
                Unsafe.As<Vector<T>, Vector<ushort>>(ref Msb) = new((ushort)(1uL << (sizeof(ushort) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<ushort>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(uint))
            {
                Unsafe.As<Vector<T>, Vector<uint>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<uint>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<uint>>(ref MinValue) = new(uint.MinValue);
                Unsafe.As<Vector<T>, Vector<uint>>(ref MaxValue) = new(uint.MaxValue);
                Unsafe.As<Vector<T>, Vector<uint>>(ref Msb) = new((uint)(1uL << (sizeof(uint) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<uint>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(ulong))
            {
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref MinValue) = new(ulong.MinValue);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref MaxValue) = new(ulong.MaxValue);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Msb) = new((ulong)(1uL << (sizeof(ulong) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(sbyte))
            {
                Unsafe.As<Vector<T>, Vector<sbyte>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<sbyte>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<sbyte>>(ref MinValue) = new(sbyte.MinValue);
                Unsafe.As<Vector<T>, Vector<sbyte>>(ref MaxValue) = new(sbyte.MaxValue);
                Unsafe.As<Vector<T>, Vector<byte>>(ref Msb) = new((byte)(1uL << (sizeof(byte) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<byte>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(short))
            {
                Unsafe.As<Vector<T>, Vector<short>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<short>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<short>>(ref MinValue) = new(short.MinValue);
                Unsafe.As<Vector<T>, Vector<short>>(ref MaxValue) = new(short.MaxValue);
                Unsafe.As<Vector<T>, Vector<ushort>>(ref Msb) = new((ushort)(1uL << (sizeof(ushort) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<ushort>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(int))
            {
                Unsafe.As<Vector<T>, Vector<int>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<int>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<int>>(ref MinValue) = new(int.MinValue);
                Unsafe.As<Vector<T>, Vector<int>>(ref MaxValue) = new(int.MaxValue);
                Unsafe.As<Vector<T>, Vector<uint>>(ref Msb) = new((uint)(1uL << (sizeof(uint) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<uint>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(long))
            {
                Unsafe.As<Vector<T>, Vector<long>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<long>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<long>>(ref MinValue) = new(long.MinValue);
                Unsafe.As<Vector<T>, Vector<long>>(ref MaxValue) = new(long.MaxValue);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Msb) = new((ulong)(1uL << (sizeof(ulong) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(float))
            {
                Unsafe.As<Vector<T>, Vector<float>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<float>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<float>>(ref MinValue) = new(float.MinValue);
                Unsafe.As<Vector<T>, Vector<float>>(ref MaxValue) = new(float.MaxValue);
                Unsafe.As<Vector<T>, Vector<uint>>(ref Msb) = new((uint)(1uL << (sizeof(uint) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<uint>>(ref Lsb) = new(1);
            }
            else if(typeof(T) == typeof(double))
            {
                Unsafe.As<Vector<T>, Vector<double>>(ref Zero) = new(0);
                Unsafe.As<Vector<T>, Vector<double>>(ref One) = new(1);
                Unsafe.As<Vector<T>, Vector<double>>(ref MinValue) = new(double.MinValue);
                Unsafe.As<Vector<T>, Vector<double>>(ref MaxValue) = new(double.MaxValue);
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Msb) = new((ulong)(1uL << (sizeof(ulong) * 8 - 1)));
                Unsafe.As<Vector<T>, Vector<ulong>>(ref Lsb) = new(1);
            }
        }
    }
}