// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY T4. DO NOT CHANGE IT. CHANGE THE .tt FILE INSTEAD.
// </auto-generated>
using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;
namespace SmartVectorDotNet;
using H = InternalHelpers;


// VectorOp.cs
partial class VectorOp
{
}

// VectorOp._BitOperations.CountLeadingZeros.cs
partial class VectorOp
{
}

// VectorOp._BitOperations.CountPopulation.cs
partial class VectorOp
{
}

// VectorOp._BitOperations.CountTrailingZeros.cs
partial class VectorOp
{
}

// VectorOp._BitOperations.IEEE754Specific.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Scale<T>(Vector<T> n, Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var n_ = ref H.Reinterpret<T, double>(n);
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(Scale_double(n_, x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var n_ = ref H.Reinterpret<T, float>(n);
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(Scale_float(n_, x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Const.cs
partial class VectorOp
{
}

// VectorOp._Const.Internal.cs
partial class VectorOp
{
}

// VectorOp._Convert.cs
partial class VectorOp
{
}

// VectorOp._Math.Abs.cs
partial class VectorOp
{
}

// VectorOp._Math.Acos.cs
partial class VectorOp
{
}

// VectorOp._Math.Acosh.cs
partial class VectorOp
{
}

// VectorOp._Math.Asin.cs
partial class VectorOp
{
}

// VectorOp._Math.Asinh.cs
partial class VectorOp
{
}

// VectorOp._Math.Atan.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Atan<T>(Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(Atan_double(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(Atan_float(x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Atan2.cs
partial class VectorOp
{
}

// VectorOp._Math.Atanh.cs
partial class VectorOp
{
}

// VectorOp._Math.Cbrt.cs
partial class VectorOp
{
}

// VectorOp._Math.Ceiling.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Ceiling<T>(Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref H.Reinterpret<T, double>(d);
            return H.Reinterpret<double, T>(Ceiling_double(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref H.Reinterpret<T, float>(d);
            return H.Reinterpret<float, T>(Ceiling_float(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Cos.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static partial Vector<T> CosBounded<T>(Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(CosBounded_double(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(CosBounded_float(x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Cosh.cs
partial class VectorOp
{
}

// VectorOp._Math.Exp.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static partial Vector<T> ExpCore<T>(Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref H.Reinterpret<T, double>(d);
            return H.Reinterpret<double, T>(ExpCore_double(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref H.Reinterpret<T, float>(d);
            return H.Reinterpret<float, T>(ExpCore_float(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Floor.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Floor<T>(Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref H.Reinterpret<T, double>(d);
            return H.Reinterpret<double, T>(Floor_double(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref H.Reinterpret<T, float>(d);
            return H.Reinterpret<float, T>(Floor_float(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.FusedMultiplyAdd.cs
partial class VectorOp
{
}

// VectorOp._Math.Log.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Log<T>(Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(Log_double(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(Log_float(x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Log10.cs
partial class VectorOp
{
}

// VectorOp._Math.Log2.cs
partial class VectorOp
{
}

// VectorOp._Math.LogA.cs
partial class VectorOp
{
}

// VectorOp._Math.MinMax.cs
partial class VectorOp
{
}

// VectorOp._Math.Pow.cs
partial class VectorOp
{
}

// VectorOp._Math.Round.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Round<T>(Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(Round_double(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(Round_float(x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Sign.cs
partial class VectorOp
{
}

// VectorOp._Math.Sin.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    private static partial Vector<T> SinBounded<T>(Vector<T> x)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var x_ = ref H.Reinterpret<T, double>(x);
            return H.Reinterpret<double, T>(SinBounded_double(x_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var x_ = ref H.Reinterpret<T, float>(x);
            return H.Reinterpret<float, T>(SinBounded_float(x_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._Math.Sinh.cs
partial class VectorOp
{
}

// VectorOp._Math.Sqrt.cs
partial class VectorOp
{
}

// VectorOp._Math.Tan.cs
partial class VectorOp
{
}

// VectorOp._Math.Tanh.cs
partial class VectorOp
{
}

// VectorOp._Math.Truncate.cs
partial class VectorOp
{
    [GeneratedCode("T4", null)]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static partial Vector<T> Truncate<T>(Vector<T> d)
        where T : unmanaged
    {
        if(typeof(T) == typeof(double))
        {
            ref readonly var d_ = ref H.Reinterpret<T, double>(d);
            return H.Reinterpret<double, T>(Truncate_double(d_));
        }
        if(typeof(T) == typeof(float))
        {
            ref readonly var d_ = ref H.Reinterpret<T, float>(d);
            return H.Reinterpret<float, T>(Truncate_float(d_));
        }
        throw new NotSupportedException();
    }

}

// VectorOp._MathEx.DivideLike.cs
partial class VectorOp
{
}

// VectorOp._MathEx.ModuloByConst.cs
partial class VectorOp
{
}

// VectorOp._Operator.cs
partial class VectorOp
{
}

// VectorOp._Operator.Modulo.cs
partial class VectorOp
{
}

// VectorOp._OperatorEx.Saturate.cs
partial class VectorOp
{
}

// VectorOp._Vector.Blend.cs
partial class VectorOp
{
}

// VectorOp._Vector.Gather.cs
partial class VectorOp
{
}

// VectorOp._Vector.Permute2.cs
partial class VectorOp
{
}

// VectorOp._Vector.Permute4.cs
partial class VectorOp
{
}

// VectorOp._Vector.Permute_Internal.cs
partial class VectorOp
{
}

